name: Docker Image CI

on:
    push:
        branches: ["master", "variants", "feature/*"]
    pull_request:
        branches: ["master", "variants"]

jobs:
 coverage:
    name: "Test Coverage"
    runs-on: "ubuntu-latest"
    if: ${{ github.event_name == 'push' }} # Publish coverage only for push commits, not PRs.
    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: setup node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        
    - name: install dependencies
      run: npm install

    - name: run tests and instrument coverage
      run: npm run test:cov

    - name: publish code coverage to code-climate (duh)
      uses: paambaati/codeclimate-action@v8.0.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        debug: true
        coverageLocations: |
          ${{github.workspace}}/.tap/report/lcov.info:lcov

